Задание №1
js-tasks-ru/js-20200821-3_nik-13 pull request #1
Opened 2020-08-24 10:30 UTC by NikAndre

Решение

2020-08-24 10:37 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Первая задача
+ should return sum of numbers
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-08-25 08:29 UTC, dosandk commented on 01-intro/1-sum/index.js
> +  if(typeof n === "number" && typeof m === "number"){
решение не требует данных проверок: `ypeof n === "number" && typeof m === "number"`
в этом можно убедиться, если посмотреть в файл с тестами, 
необходимо проверки убрать

2020-08-25 08:29 UTC, dosandk requested changes
необходимо внести изменения согласно коментариям

2020-08-25 16:50 UTC, jsru commented
@dosandk ping :)

2020-08-25 19:37 UTC, dosandk approved these changes

2020-08-25 19:37 UTC, merged